# syntax=docker/dockerfile:1.3-labs
FROM denoland/deno:alpine AS builder

WORKDIR /app

COPY package.json deno.lock ./
RUN deno i
COPY . .

RUN deno run build

FROM nginx:latest

COPY --from=builder /app/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]