FROM golang:1.25.1-alpine3.22

WORKDIR /src

RUN go install github.com/air-verse/air@latest

COPY backend/go.mod backend/go.sum ./

RUN go mod download

COPY docker/backend/entrypoint.dev.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
