version: '3.8'

services:

  db:
    container_name: "${POSTGRES_CONTAINER_NAME}"
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}

  backend:
    container_name: "${BACKEND_CONTAINER_NAME}"
    image: "${BACKEND_IMAGE_NAME}"
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - CONTAINER_NAME=${BACKEND_CONTAINER_NAME}
      - DB_HOST=${DB_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - db # db service will start prior to backend

  frontend:
    container_name: "${FRONTEND_CONTAINER_NAME}"
    image: "${FRONTEND_IMAGE_NAME}"
    depends_on:
      - backend

  nginx:
    container_name: "${NGINX_CONTAINER_NAME}"
    image: nginx:1.27.0
    depends_on:
      - backend
      - frontend
