version: '3.8'

services:

  db:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE} # database named ${POSTGRES_DB} will be created inside container
    # volumes:
      # - db-data:/var/lib/postgresql/data
      # Mount data initialization script
      # - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh  # Mount your initialization script
    ports:
      - "${DB_PORT}:${POSTGRES_PORT}"

  backend:
    container_name: "${BACKEND_CONTAINER_NAME}"
    image: "${BACKEND_IMAGE_NAME}"
    environment:
      - CONTAINER_NAME=${BACKEND_CONTAINER_NAME}
      # DB_HOST hostname/ip address to connect to database.
      # We can use the service name in docker-compose
      - DB_HOST=db # docker-compose service name referred to in docker-compose.yaml
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
    depends_on:
      - db # db service will start prior to backend

  frontend:
    container_name: "${FRONTEND_CONTAINER_NAME}"
    image: "${FRONTEND_IMAGE_NAME}"
    depends_on:
      - backend

  nginx:
    container_name: "${NGINX_CONTAINER_NAME}"
    image: "${NGINX_IMAGE_NAME}"
    depends_on:
      - backend
      - frontend