FROM node:26.3.0-alpine3.22 AS builder

WORKDIR /app

COPY frontend/package.json frontend/package-lock.json ./

RUN npm install

COPY frontend/ .

COPY docker/frontend/entrypoint.dev.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
