package marketmath

import (
	"sort"

	"socialpredict/internal/domain/boundary"
)

// SellDustCalculator defines how to compute dust for a sell bet.
type SellDustCalculator interface {
	DustForSell(sellBet boundary.Bet, allBets []boundary.Bet) int64
}

// ConstantSellDustCalculator returns a fixed dust amount for every sell.
type ConstantSellDustCalculator struct {
	DustPerSell int64
}

func (c ConstantSellDustCalculator) DustForSell(sellBet boundary.Bet, allBets []boundary.Bet) int64 {
	if sellBet.Amount < 0 {
		return c.DustPerSell
	}
	return 0
}

var defaultSellDustCalculator = ConstantSellDustCalculator{DustPerSell: 1}

type marketDustCalculator struct {
	volumeCalculator VolumeCalculator
	sellCalculator   SellDustCalculator
}

var defaultMarketDustCalculator = marketDustCalculator{
	volumeCalculator: defaultVolumeCalculator,
	sellCalculator:   defaultSellDustCalculator,
}

// GetMarketVolumeWithDust returns the market volume including accumulated dust from selling
// This ensures currency conservation by accounting for dust that remains in the market
func GetMarketVolumeWithDust(bets []boundary.Bet) int64 {
	return defaultMarketDustCalculator.VolumeWithDust(bets)
}

// calculateDustStack computes total dust accumulated from all sell transactions
// Uses O(n) single-pass algorithm with chronological processing
func calculateDustStack(bets []boundary.Bet) int64 {
	return defaultMarketDustCalculator.Dust(bets)
}

// GetMarketDustWithCalculator allows callers to supply a custom dust calculator.
// Falls back to default dust behavior if a nil calculator is provided.
func GetMarketDustWithCalculator(bets []boundary.Bet, calculator SellDustCalculator) int64 {
	if calculator == nil {
		calculator = defaultSellDustCalculator
	}
	return marketDustCalculator{
		volumeCalculator: defaultVolumeCalculator,
		sellCalculator:   calculator,
	}.Dust(bets)
}

func calculateDustStackWithCalculator(bets []boundary.Bet, calculator SellDustCalculator) int64 {
	if calculator == nil {
		return 0
	}

	var totalDust int64
	for _, bet := range bets {
		if bet.Amount >= 0 {
			continue
		}
		totalDust += calculator.DustForSell(bet, bets)
	}
	return totalDust
}

// calculateDustForSell determines dust generated by a specific sell transaction
// This is a placeholder implementation - actual dust calculation will depend on
// the selling mechanism and how shares are valued at the time of sale
func calculateDustForSell(sellBet boundary.Bet, allBets []boundary.Bet) int64 {
	return defaultMarketDustCalculator.DustForSell(sellBet, allBets)
}

// GetMarketDust calculates accumulated dust for a market
// This is a utility function for dust-related calculations
func GetMarketDust(bets []boundary.Bet) int64 {
	return defaultMarketDustCalculator.Dust(bets)
}

func sortBetsChronologically(bets []boundary.Bet) []boundary.Bet {
	sortedBets := make([]boundary.Bet, len(bets))
	copy(sortedBets, bets)
	sort.Slice(sortedBets, func(i, j int) bool {
		return sortedBets[i].PlacedAt.Before(sortedBets[j].PlacedAt)
	})
	return sortedBets
}

func (c marketDustCalculator) VolumeWithDust(bets []boundary.Bet) int64 {
	return c.volumeCalculator.Volume(bets) + c.Dust(bets)
}

func (c marketDustCalculator) Dust(bets []boundary.Bet) int64 {
	if len(bets) == 0 {
		return 0
	}
	return calculateDustStackWithCalculator(sortBetsChronologically(bets), c.sellCalculator)
}

func (c marketDustCalculator) DustForSell(sellBet boundary.Bet, allBets []boundary.Bet) int64 {
	if c.sellCalculator == nil {
		return 0
	}
	return c.sellCalculator.DustForSell(sellBet, allBets)
}
