<!-- This file is generated by bin/buildTutorial.ts. Do not edit by hand. -->
<script module lang="ts">
  import type { FeatureKey } from '$lib/components/DemoMarketCard.svelte';

  export type FeatureDescription = {
    key: FeatureKey;
    label: string;
    detail: string;
  };
</script>

<script lang="ts">
  'use runes';

  import DemoMarketCard from '$lib/components/DemoMarketCard.svelte';
  import MarketCard, { type Market } from '$lib/components/MarketCard.svelte';

  const { open = false, onClose, onComplete } = $props<{
    open: boolean;
    onClose?: () => void;
    onComplete?: () => void;
  }>();
  const total = 5;

  const b = 40; // LMSR liquidity
  const baseYes = 50;
  const baseNo = 50;

  let index = $state(0);
  let completed = $state(false);
  let resolved = $state(false);
  let hoveredFeature = $state<FeatureKey | null>(null);

  let yesBuy = $state<number>(0);
  let noBuy = $state<number>(0);

  const mockMarket: Market = {
    title: 'Will Apple release a foldable iPhone in 2025?',
    yes: 62,
    no: 38,
    community: '1,842 predictions',
    resolves: 'Oct 9 · Apple Event',
    trend: 12,
    liquidity: 'deep',
    category: 'Tech',
    sparkline: '0,20 10,18 20,16 30,12 40,15 50,10 60,12 70,9 80,11 90,7 100,10 110,6 120,9'
  };

  const priceYes = $derived(toCents(priceLmsr(baseYes + yesBuy, baseNo + noBuy)));
  const priceNo = $derived(100 - priceYes);
  const displayedMarket = $derived(
    resolved ? { ...mockMarket, yes: 100, no: 0 } : { ...mockMarket, yes: priceYes, no: priceNo }
  );
  const costYes = $derived(tradeCost(yesBuy, 0));
  const costNo = $derived(tradeCost(0, noBuy));
  const activeSide = $derived(yesBuy > 0 ? 'yes' : noBuy > 0 ? 'no' : null);
  const shareCost = $derived(
    yesBuy > 0
      ? Number(((yesBuy * priceYes) / 100).toFixed(2))
      : noBuy > 0
        ? Number(((noBuy * priceNo) / 100).toFixed(2))
        : 0
  );
  const payoutYes = $derived(Number((yesBuy * 1).toFixed(2)));
  const netProfit = $derived(resolved ? Number((payoutYes - shareCost).toFixed(2)) : 0);
  const netProfitPercent = $derived(
    resolved && shareCost > 0 ? Number(((netProfit / shareCost) * 100).toFixed(2)) : 0
  );
  const payoutPositive = $derived(payoutYes > 0);

  $effect(() => {
    if (!open) {
      index = 0;
      completed = false;
      resolved = false;
      yesBuy = 0;
      noBuy = 0;
      hoveredFeature = null;
    }
  });

  function close() {
    index = 0;
    completed = false;
    onClose?.();
  }

  function next() {
    if (index < total - 1) {
      index += 1;
    } else {
      completed = true;
      onComplete?.();
    }
  }

  function back() {
    if (index === 0) return;
    index = Math.max(0, index - 1);
  }

  function resolveMarket() {
    if (resolved) return;
    resolved = true;
  }

  function resetResolution() {
    if (!resolved) return;
    resolved = false;
  }

  function priceLmsr(qYes: number, qNo: number) {
    const expYes = Math.exp(qYes / b);
    const expNo = Math.exp(qNo / b);
    return expYes / (expYes + expNo);
  }

  function toCents(value: number) {
    return Math.round(value * 100);
  }

  function cost(qYes: number, qNo: number) {
    return b * Math.log(Math.exp(qYes / b) + Math.exp(qNo / b));
  }

  function tradeCost(deltaYes: number, deltaNo: number) {
    const before = cost(baseYes, baseNo);
    const after = cost(baseYes + deltaYes, baseNo + deltaNo);
    return Math.max(0, after - before);
  }

  function handleYesInput(event: Event) {
    const value = Number((event.currentTarget as HTMLInputElement).value);
    yesBuy = value;
    noBuy = 0;
  }

  function handleNoInput(event: Event) {
    const value = Number((event.currentTarget as HTMLInputElement).value);
    noBuy = value;
    yesBuy = 0;
  }
</script>

<div
  class={open ? 'overlay overlay--open' : 'overlay overlay--hidden'}
  role="dialog"
  aria-modal="true"
  aria-label="SocialPredict tutorial"
>
  <div class="modal">
    <button class="close" aria-label="Close tutorial" type="button" onclick={close}>✕</button>

    {#if !completed}
      <div class="layout">
        <div class="instructions">
          <div class="eyebrow">Step {index + 1} of {total}</div>
          {#if index === 0}
            <h3 class="demo-title">{@html "A prediction market works like this…"}</h3>
            <p>{@html "<p class=\"spaced\">You buy YES/NO shares on real-world events.</p>\n<p class=\"spaced\">All markets start at 50¢/50¢ representing equal probability for YES and NO outcomes.</p>\n<p class=\"spaced\">Share prices move with demand, reflecting the crowd’s collective forecast.</p>\n<p>This is the \"<em>Wisdom of the Crowd</em>\" in action.</p>"}</p>
            <div class="note">{@html "<p>Tip: Share prices represent outcome probabilities. For example, if the market price for YES is 62¢, the market expects that there is a ~62% chance it will resolve YES.</p>"}</div>
          {:else if index === 1}
            <h3 class="demo-title">{@html "Tour a market…"}</h3>
            <div class="note">{@html "Hover over each bullet to highlight its feature on the market card."}</div>
            <ul class="feature-list">
              <li
                class={hoveredFeature === 'category' ? 'highlighted' : ''}
                onmouseenter={() => (hoveredFeature = 'category')}
                onmouseleave={() => (hoveredFeature = null)}
              >
                <strong>Market type:</strong>
                Which arena this market belongs to (Politics, Tech, Sports, etc).
              </li>
              <li
                class={hoveredFeature === 'resolution' ? 'highlighted' : ''}
                onmouseenter={() => (hoveredFeature = 'resolution')}
                onmouseleave={() => (hoveredFeature = null)}
              >
                <strong>Resolution time:</strong>
                When the market will settle and pay out.
              </li>
              <li
                class={hoveredFeature === 'question' ? 'highlighted' : ''}
                onmouseenter={() => (hoveredFeature = 'question')}
                onmouseleave={() => (hoveredFeature = null)}
              >
                <strong>Market question:</strong>
                The exact phrasing of what resolves YES vs NO.
              </li>
              <li
                class={hoveredFeature === 'prices' ? 'highlighted' : ''}
                onmouseenter={() => (hoveredFeature = 'prices')}
                onmouseleave={() => (hoveredFeature = null)}
              >
                <strong>Prices:</strong>
                YES/NO quotes show implied probability; they change with trades.
              </li>
              <li
                class={hoveredFeature === 'trend' ? 'highlighted' : ''}
                onmouseenter={() => (hoveredFeature = 'trend')}
                onmouseleave={() => (hoveredFeature = null)}
              >
                <strong>Trend:</strong>
                Recent momentum signal to see which outcome is heating up.
              </li>
              <li
                class={hoveredFeature === 'liquidity' ? 'highlighted' : ''}
                onmouseenter={() => (hoveredFeature = 'liquidity')}
                onmouseleave={() => (hoveredFeature = null)}
              >
                <strong>Liquidity:</strong>
                Indicates how well funded the market is and how many participants are active within it.
              </li>
              <li
                class={hoveredFeature === 'community' ? 'highlighted' : ''}
                onmouseenter={() => (hoveredFeature = 'community')}
                onmouseleave={() => (hoveredFeature = null)}
              >
                <strong>Community:</strong>
                How many predictions/comments—shows activity and interest.
              </li>
              <li
                class={hoveredFeature === 'cta' ? 'highlighted' : ''}
                onmouseenter={() => (hoveredFeature = 'cta')}
                onmouseleave={() => (hoveredFeature = null)}
              >
                <strong>Action:</strong>
                How users place trades.
              </li>
            </ul>
          {:else if index === 2}
            <h3 class="demo-title">{@html "See how prices change…"}</h3>
            <p>{@html "<p class=\"spaced\">Drag the sliders to see how market prices react to trades by users.</p>\n<p class=\"spaced\">Notice how buying more shares of one outcome pushes its price up, while the opposing outcome's price drops accordingly.</p>\n<p>Prices are determined by supply and demand. The more users buy YES shares, the higher the price for YES becomes, indicating increased confidence in that outcome.</p>"}</p>
            <div class="note">{@html "Tip: If you were actually trading, your actual cost would be set by the price at the time of your trade."}</div>
          {:else if index === 3}
            <h3 class="demo-title">{@html "Watch the market resolve — rewards arrive instantly…"}</h3>
            <p>{@html "<p class=\"spaced\">When an event settles (when its market \"resolves\"), shareholders are paid out.</p>\n<p class=\"spaced\">If you hold shares of the winning outcome, you receive 100% value for each share you own.</p>\n<p class=\"spaced\">If the market resolves to \"YES\", holders of YES shares are paid $1 (100% value) for each of their shares.</p>\n<p class=\"spaced\">Losing shares become worthless.</p>\n<p class=\"spaced\">Funds are credited to your account instantly, ready for withdrawal or reinvestment.</p>\n<p>Let's assume you bought your shares for the current price of your chosen outcome.</p>"}</p>
            <div class="note">{@html "Press the \"Resolve Market to YES\" button to see how your payout is calculated based on your purchase price versus the resolution outcome."}</div>
          {:else}
            <h3 class="demo-title">{@html "Join the SocialPredict community…"}</h3>
            <p>{@html "Follow top forecasters, join prediction threads, and see sentiment move in real time."}</p>
          {/if}
        </div>

        <div class="demo">
          <div class="demo__label">Mock market</div>
          <div
            class={resolved ? 'card-shell resolved' : 'card-shell'}
            role="presentation"
            onmouseleave={() => (hoveredFeature = null)}
          >
            <DemoMarketCard
              market={displayedMarket}
              highlightFeature={index === 1 ? hoveredFeature : null}
              onFeatureHover={(key) => (hoveredFeature = key)}
            />
            {#if resolved}
              <div class="resolved-badge">Resolved</div>
            {/if}
          </div>

          {#if index === 2}
            <div class="sliders">
              <div class="slider-row">
                <div class="slider-meta">
                  <div class="tag yes">YES</div>
                  <div class="value">{yesBuy} shares</div>
                </div>
                <input
                  type="range"
                  min="0"
                  max="100"
                  step="1"
                  value={yesBuy}
                  oninput={handleYesInput}
                />
              </div>
              <div class="slider-row">
                <div class="slider-meta">
                  <div class="tag no">NO</div>
                  <div class="value">{noBuy} shares</div>
                </div>
                <input
                  type="range"
                  min="0"
                  max="100"
                  step="1"
                  value={noBuy}
                  oninput={handleNoInput}
                />
              </div>
              <div class="pill">
                <span>Cost</span>
                {#if activeSide === 'yes'}
                  <span>Cost to buy {yesBuy} shares YES: $ {costYes.toFixed(2)}</span>
                {:else if activeSide === 'no'}
                  <span>Cost to buy {noBuy} shares NO: $ {costNo.toFixed(2)}</span>
                {:else}
                  <span>Move a slider to see cost</span>
                {/if}
              </div>
            </div>
          {:else if index === 3}
            <div class="resolve-box">
              <div class="resolve-actions">
                <button class="primary" type="button" onclick={resolveMarket} disabled={resolved}>
                  {resolved ? 'Market is Resolved' : 'Resolve Market to YES'}
                </button>
                <button class="ghost" type="button" onclick={resetResolution} disabled={!resolved}>
                  Reset resolution
                </button>
              </div>
              <div class="resolve-meta">
                <div>You own: {yesBuy} YES / {noBuy} NO</div>
                {#if resolved}
                  <div class="cost">What you paid for your shares: $ {shareCost.toFixed(2)}</div>
                {/if}
                <div class={payoutPositive ? 'payout up' : 'payout down'}>
                  {#if resolved}
                    <div>Your Payout: $ {payoutYes.toFixed(2)}</div>
                    <div>
                      Net {netProfit >= 0 ? 'profit' : 'loss'}: $ {netProfit.toFixed(2)} (
                      {netProfitPercent}%
                      )
                    </div>
                  {:else}
                    <div>Adjust the sliders to explore potential outcomes.</div>
                  {/if}
                </div>
              </div>
            </div>
          {/if}
        </div>
      </div>

      <div class="progress">
        <div class={index === 0 ? 'dot active' : 'dot'}></div>
        <div class={index === 1 ? 'dot active' : 'dot'}></div>
        <div class={index === 2 ? 'dot active' : 'dot'}></div>
        <div class={index === 3 ? 'dot active' : 'dot'}></div>
        <div class={index === 4 ? 'dot active' : 'dot'}></div>
      </div>

      <div class="actions">
        {#if index > 0}
          <button class="secondary ghost" type="button" onclick={back}>Back</button>
        {/if}
        <button class="primary" type="button" onclick={next}>
          {index === total - 1 ? 'Finish' : 'Next'}
        </button>
      </div>
    {:else}
      <div class="layout">
        <div class="instructions">
          <div class="header">
            <div class="eyebrow">Ready to trade?</div>
            <h3>Join the SocialPredict crowd</h3>
            <p>
              You just walked through how to place a YES/NO order. Create an account to follow
              forecasters, join threads, and start predicting live markets.
            </p>
          </div>
          <div class="cta-row single">
            <button class="primary" type="button">Create Account</button>
          </div>
        </div>
      </div>
      <div class="actions">
        <button class="secondary" type="button" onclick={close}>Close</button>
      </div>
    {/if}
  </div>
</div>

<style>
  .overlay {
    position: fixed;
    inset: 0;
    background: rgba(10, 11, 16, 0.65);
    display: grid;
    place-items: center;
    z-index: 20;
    padding: 1.5rem;
    opacity: 1;
    pointer-events: auto;
    visibility: visible;
    transition: opacity 150ms ease-out, visibility 150ms ease-out;
  }

  .overlay.overlay--hidden {
    opacity: 0;
    pointer-events: none;
    visibility: hidden;
  }

  .modal {
    position: relative;
    width: min(78vw, 1100px);
    min-height: 60vh;
    padding: 1.6rem 1.9rem;
    border-radius: 1.2rem;
    background: var(--panel, #12131a);
    border: 1px solid var(--border, rgba(255, 255, 255, 0.1));
    box-shadow: 0 20px 50px rgba(0, 0, 0, 0.45),
      0 0 0 1px var(--color-primary-soft, rgba(159, 107, 255, 0.18));
    display: grid;
    gap: 1.2rem;
  }

  .layout {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 1.2rem;
    align-items: start;
  }

  .close {
    position: absolute;
    top: 0.8rem;
    right: 0.8rem;
    background: var(--panel, rgba(255, 255, 255, 0.05));
    border: 1px solid var(--border, rgba(255, 255, 255, 0.12));
    color: var(--text, #e6e4ff);
    border-radius: 50%;
    width: 36px;
    height: 36px;
    cursor: pointer;
    font-size: 1rem;
  }

  .instructions {
    display: grid;
    gap: 0.75rem;
    align-content: start;
  }

  .header {
    display: grid;
    gap: 0.35rem;
  }

  .eyebrow {
    display: inline-flex;
    align-items: center;
    gap: 0.4rem;
    padding: 0.35rem 0.7rem;
    border-radius: 999px;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    font-size: 0.78rem;
    color: var(--color-primary, #9f6bff);
    background: var(--color-primary-soft, rgba(159, 107, 255, 0.14));
    border: 1px solid color-mix(in srgb, var(--color-primary, #9f6bff) 55%, transparent);
    width: fit-content;
  }

  h3 {
    margin: 0.1rem 0 0;
    color: var(--text, #f7f6ff);
  }

  .demo-title {
    margin: 0.1rem 0 0;
    color: var(--text, #f7f6ff);
    font-weight: 900;
  }

  p {
    margin: 0;
    color: var(--text-subtle, #c4c8df);
  }

  .spaced {
    margin-bottom: 1rem;
  }

  .note {
    margin-top: 0.3rem;
    padding: 0.65rem 0.8rem;
    border-radius: 0.75rem;
    background: var(--panel, rgba(255, 255, 255, 0.04));
    border: 1px dashed var(--border, rgba(255, 255, 255, 0.12));
    color: var(--text, #e6e4ff);
  }

  .progress {
    display: flex;
    gap: 0.4rem;
  }

  .dot {
    width: 12px;
    height: 12px;
    border-radius: 50%;
    background: rgba(255, 255, 255, 0.12);
    border: 1px solid rgba(255, 255, 255, 0.1);
  }

  .dot.active {
    background: linear-gradient(
      135deg,
      var(--color-primary, #6a3ff5),
      var(--color-accent, #35e2d1)
    );
    box-shadow: 0 0 12px color-mix(in srgb, var(--color-primary, #6a3ff5) 60%, transparent);
  }

  .actions {
    display: flex;
    justify-content: flex-end;
    gap: 0.7rem;
    align-items: center;
  }

  .demo {
    display: grid;
    gap: 0.75rem;
    align-content: start;
  }

  .demo__label {
    font-size: 0.9rem;
    color: var(--text-subtle, #c4c8df);
    text-transform: uppercase;
    letter-spacing: 0.08em;
  }

  .feature-list {
    list-style: disc;
    padding-left: 1.3rem;
    display: grid;
    gap: 0.5rem;
    color: var(--text, #dcd9f4);
  }

  .feature-list li {
    list-style: disc;
  }

  .feature-list li.highlighted {
    color: var(--color-accent, #35e2d1);
    text-shadow: 0 0 10px color-mix(in srgb, var(--color-accent, #35e2d1) 55%, transparent);
  }

  .feature-list strong {
    color: var(--text, #f7f6ff);
  }

  .sliders {
    display: grid;
    gap: 0.85rem;
    margin-top: 0.5rem;
  }

  .slider-row {
    display: grid;
    gap: 0.35rem;
  }

  .slider-meta {
    display: flex;
    justify-content: space-between;
    align-items: center;
    color: var(--text, #e6e4ff);
    font-weight: 700;
  }

  .slider-row input[type='range'] {
    accent-color: var(--color-primary, #6a3ff5);
  }

  .slider-row input[type='range']::-webkit-slider-thumb {
    box-shadow: 0 0 0 6px color-mix(in srgb, var(--color-primary, #6a3ff5) 35%, transparent);
  }

  .tag {
    padding: 0.25rem 0.6rem;
    border-radius: 0.7rem;
    font-size: 0.85rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }

  .tag.yes {
    background: var(--color-accent-soft, rgba(53, 226, 209, 0.14));
    color: var(--color-accent, #35e2d1);
    border: 1px solid color-mix(in srgb, var(--color-accent, #35e2d1) 55%, transparent);
  }

  .tag.no {
    background: var(--color-danger-soft, rgba(255, 111, 97, 0.12));
    color: var(--color-danger, #ff8d7f);
    border: 1px solid color-mix(in srgb, var(--color-danger, #ff8d7f) 55%, transparent);
  }

  .pill {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 0.75rem 0.9rem;
    border-radius: 0.85rem;
    background: var(--panel, rgba(255, 255, 255, 0.04));
    border: 1px solid var(--border, rgba(255, 255, 255, 0.08));
    font-weight: 700;
    color: var(--text, #f4f1ff);
  }

  .cta-row {
    display: flex;
    gap: 0.75rem;
  }

  .cta-row.single {
    justify-content: flex-start;
  }

  .card-shell {
    position: relative;
  }

  .resolved .resolved-badge {
    display: inline-flex;
    align-items: center;
    gap: 0.35rem;
    padding: 0.35rem 0.7rem;
    border-radius: 0.9rem;
    background: var(--color-accent-soft, rgba(53, 226, 209, 0.18));
    color: var(--text, #e6e4ff);
    font-weight: 800;
    position: absolute;
    top: 0.75rem;
    right: 0.75rem;
    box-shadow: 0 10px 20px rgba(0, 0, 0, 0.25);
  }

  .resolve-box {
    display: grid;
    gap: 0.55rem;
    align-content: start;
  }

  .resolve-actions {
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem;
  }

  .resolve-box .primary {
    width: fit-content;
  }

  .resolve-meta {
    display: grid;
    gap: 0.2rem;
    color: var(--text-subtle, #dcd9f4);
    font-weight: 700;
  }

  .cost {
    color: var(--text-muted, #a9aec9);
  }

  .payout.up {
    color: var(--color-accent, #35e2d1);
  }

  .payout.down {
    color: var(--color-danger, #ff8d7f);
  }

  button.primary,
  button.secondary,
  button.ghost {
    padding: 0.85rem 1.2rem;
    border-radius: 0.95rem;
    font-weight: 800;
    font-size: 1rem;
    letter-spacing: 0.01em;
    border: none;
    cursor: pointer;
  }

  button.primary {
    background: linear-gradient(
      135deg,
      var(--color-primary, #6a3ff5),
      var(--color-accent, #9f6bff)
    );
    color: var(--color-text-light, #e6e4ff);
    box-shadow: 0 14px 36px color-mix(in srgb, var(--color-primary, #6a3ff5) 45%, transparent);
  }

  button.secondary {
    background: var(--panel, rgba(255, 255, 255, 0.06));
    color: var(--text, #e6e4ff);
    border: 1px solid var(--border, rgba(255, 255, 255, 0.1));
  }

  button.ghost {
    background: transparent;
    color: var(--text, #e6e4ff);
    border: 1px solid var(--border, rgba(255, 255, 255, 0.14));
  }

  button:disabled {
    opacity: 0.5;
    cursor: not-allowed;
    box-shadow: none;
  }

  button.primary:hover {
    transform: translateY(-1px);
  }

  button.secondary:hover,
  button.ghost:hover {
    border-color: color-mix(
      in srgb,
      var(--color-primary, #6a3ff5) 65%,
      var(--border, #4b5563) 35%
    );
  }

  @media (max-width: 900px) {
    .modal {
      width: min(95vw, 760px);
    }

    .layout {
      grid-template-columns: 1fr;
    }

    .cta-row {
      flex-direction: column;
    }

    .actions {
      flex-direction: column;
      align-items: stretch;
    }

    .actions button {
      width: 100%;
    }
  }
</style>
