version: '3.8'

services:
  db:
    networks:
      - backend_network

  backend:
    environment:
      - ENVIRONMENT=production
    networks:
      - backend_network

  frontend:
    environment:
      - ENVIRONMENT=production
    networks:
      - backend_network

  nginx:
    ports:
      - "80:80"  # Only expose Nginx on port 80 in production
    networks:
      - backend_network
      - frontend_network

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge
