services:

  db:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres:16.6-alpine3.20
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    networks:
      - socialpredict_internal_network
    env_file:
      - ${ENV_PATH}

  backend:
    container_name: "${BACKEND_CONTAINER_NAME}"
    image: ghcr.io/openpredictionmarkets/socialpredict-backend
    restart: unless-stopped
    networks:
      - socialpredict_internal_network
    env_file:
      - ${ENV_PATH}
    depends_on:
      - db

  frontend:
    container_name: "${FRONTEND_CONTAINER_NAME}"
    image: ghcr.io/openpredictionmarkets/socialpredict-frontend
    restart: unless-stopped
    networks:
      - socialpredict_internal_network
    env_file:
      - ${ENV_PATH}
    depends_on:
      - backend

  webserver:
    container_name: "${NGINX_CONTAINER_NAME}"
    image: nginx:latest
    restart: unless-stopped
    environment:
      ENVIRONMENT: ${APP_ENV}
      DOMAIN: ${DOMAIN}
      BACKEND_PORT: ${BACKEND_PORT}
      FRONTEND_PORT: ${REACT_PORT}
    volumes:
      - ../data/nginx/vhosts/prod:/etc/nginx/templates/
    networks:
      - socialpredict_internal_network
      - socialpredict_external_network
    env_file:
      - ${ENV_PATH}
    depends_on:
      - backend
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.social-predict.rule=Host(`${DOMAIN}`)"

  traefik:
    container_name: "${TRAEFIK_CONTAINER_NAME}"
    image: traefik:v3.5
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    networks:
      - socialpredict_external_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../data/traefik/config/traefik.yaml:/etc/traefik/traefik.yml:ro
      - ../data/traefik/config/acme.json:/acme.json
      - ../data/traefik/logs/:/logs/

networks:
  socialpredict_internal_network:
    name: socialpredict_internal_network
  socialpredict_external_network:
    name: socialpredict_external_network
    external: true
