services:

  db:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres:16.6-alpine3.20
    environment:
      #      ENVIRONMENT: ${APP_ENV}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${POSTGRES_PORT}"
    networks:
      - database_network
    env_file:
      - ${ENV_PATH}

  backend:
    container_name: "${BACKEND_CONTAINER_NAME}"
    image: "${BACKEND_IMAGE_NAME}"
    environment:
      ENVIRONMENT: ${APP_ENV}
      CONTAINER_NAME: ${BACKEND_CONTAINER_NAME}
      DB_HOST: db
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
    ports:
      - "${BACKEND_HOSTPORT}:${BACKEND_PORT}"
    volumes:
      - ../backend:/backend
      - ${ENV_PATH}:/backend/.env.dev
    command: reflex -r '\.go$' -s -- sh -c './supervisor.sh'
    tty: true
    networks:
      - database_network
      - frontend_network
    env_file:
      - ${ENV_PATH}
    depends_on:
      - db

  frontend:
    container_name: "${FRONTEND_CONTAINER_NAME}"
    image: "${FRONTEND_IMAGE_NAME}"
    environment:
      ENVIRONMENT: ${APP_ENV}
      DOMAIN: "https://${DOMAIN}"
    networks:
      - frontend_network
    env_file:
      - ${ENV_PATH}
    volumes:
      - ../frontend:/app
      - /app/node_modules
    stdin_open: true
    ports:
      - "${REACT_HOSTPORT}:${REACT_PORT}"
    depends_on:
      - backend

  webserver:
    container_name: "${NGINX_CONTAINER_NAME}"
    image: nginx:latest
    environment:
      ENVIRONMENT: ${APP_ENV}
      DOMAIN: ${DOMAIN}
      BACKEND_PORT: ${BACKEND_PORT}
      FRONTEND_PORT: ${REACT_PORT}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../data/nginx/vhosts/prod:/etc/nginx/templates/
      - ../data/certbot/conf:/etc/letsencrypt
      - ../data/certbot/www:/var/www/certbot
    restart: always
    networks:
      - database_network
      - frontend_network
    env_file:
      - ${ENV_PATH}
    depends_on:
      - backend
      - frontend

  certbot:
    container_name: "${CERTBOT_CONTAINER_NAME}"
    image: certbot/certbot:latest
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ../data/certbot/conf:/etc/letsencrypt
      - ../data/certbot/www:/var/www/certbot

networks:
  database_network:
    driver: bridge
  frontend_network:
    driver: bridge
