#!/bin/bash

source ../.env.dev

# Check if the correct number of arguments is provided
if [[ "$#" -ne 1 ]]; then
    echo "Usage: $0 host_location"
    exit 1
fi

# Assigning argument to variable
HOST_LOCATION=$1

# Filename for the backup
BACKUP_FILE="socialpredict_dev_og_backup_$(date +"%Y%m%d_%H%M%S").sql"

# Run pg_dump inside the container
echo "Creating backup of the ${DATABASE_NAME} database..."
docker exec -t "${POSTGRES_CONTAINER_NAME}" pg_dump -U "${POSTGRES_USER}" "devdb" > "${BACKUP_FILE}"

# Check if the backup was successful
if [[ $? -eq 0 ]]; then
    echo "Backup created successfully."
else
    echo "Failed to create backup."
    exit 2
fi

# Moving the backup file to the host location
echo "Moving backup file to ${HOST_LOCATION}..."
mv "${BACKUP_FILE}" "${HOST_LOCATION}"

# Check if the move was successful
if [[ $? -eq 0 ]]; then
    echo "Backup file moved successfully."
else
    echo "Failed to move backup file."
    exit 3
fi

echo "Backup process completed."