name: Deploy To Staging

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Deploy SocialPredict to Staging
        if: github.event.pull_request.merged == true
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: openpredictionmarkets/ansible_playbooks
          event-type: deploy-to-staging
