name: Docker Hub images - build & push
on:
  push:
    branches:
    - devops-docker

env:
  IMAGE_BASE: ${{ secrets.IMAGE_BASE || 'jmartincufre/socialpredict' }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push backend
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/backend/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ${{ env.IMAGE_BASE }}-backend:latest
          ${{ env.IMAGE_BASE }}-backend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push frontend
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/frontend/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ${{ env.IMAGE_BASE }}-frontend:latest
          ${{ env.IMAGE_BASE }}-frontend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
