name: Lighthouse CI

on:
  
  workflow_run:
    workflows: ["Deploy Prod configuration"]
    types: [completed]
    branches:
    - 'main'
    - 'v*'

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            ${{ secrets.HOST }}/
            ${{ secrets.HOST }}/polls
            ${{ secrets.HOST }}/markets
          budgetPath: ./scripts/lighthouse # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage